version: '2.0'
services:
  app:
    build: .
    ports:
      - "8080:8080"
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    volumes:
      - patreon-statistics:/var/lib/pgsql

volumes:
  patreon-statistics:
